name: Scorecard supply-chain security

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * 1" # weekly check

permissions:
  contents: read
  security-events: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        continue-on-error: true
        with:
          results_file: results.json
          results_format: json # keep as JSON
          publish_results: true # still publishes to Security tab

      - name: Save Scorecard results as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: scorecard-results
          path: results.json
