name: Scorecard supply-chain security

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * 1" # weekly check

permissions:
  contents: read
  security-events: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        continue-on-error: true
        with:
          results_file: results.json
          results_format: json # keep as JSON
          publish_results: false # still publishes to Security tab

      - name: Extract Score
        run: |
          score=$(jq '.score' results.json)
          echo "Score is: $score"

      - name: Save Scorecard results as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: scorecard-results
          path: results.json
